name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1

    - name: FTP Upload
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: curl -T index.html ftp://alfa3040.alfahosting-server.de/index.html --user "$FTP_USERNAME:FTP_PASSWORD"

